name: Coded Concepts
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfaea'
    - '#9dd4ce'
    - '#2a1605'
    - '#8a445f'
    - '#f1cc4e'
  brandStrength: 0.4375
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
