name: Coded Concepts
favicon: null
layout_spectrum: 0.3789180484600365
typography_spectrum: 0.770520779537037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5949093396775424
  lightness: 0.7203688859008253
  saturation: 0.4399556601420045
  rhythmicContrast: 0.25017377897165716
purpose: []
